### ISSUE TITLE
Use dataframe instead of folder structure

### ISSUE THREAD

**Issue by rbunn80110** [tcapelle/action_recognition#12]
The current implementation depends on the video frames being in folders.  I have a csv file with rows containing the folders and the corresponding label.  I seem to be going around in circles trying to figure out where the best place to make the code change would be.  I'm sure this should be a fairly simple change, however I'm just not seeing where the best place to make the change would be.  I think part of my problem is that the current implementation uses the folder path to obtain the label, whereas my label is associated with the folder name in the dataframe.

**Comment by tcapelle** [comment]
Hey,
This should be pretty straight forward using the `DataBlock` API. Just define your `get_x` and `get_y`, with the corresponding columns in the dataframe.

**Comment by rbunn80110** [comment]
yes, that was it.  I was making it way too complicated.  Thanks!

**Comment by tcapelle** [comment]
I the last update, I removed the Block API. Sorry if that hurts your dev.
The mid level API is now the preferred way, and it is very well documented.
