### ISSUE TITLE
[Question] : Is it possible to use same code for UCF - CRCV dataset ? 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [tcapelle/action_recognition#17]
Hi ,
I'm trying to  build video classification model using small subset of UCF-CRCV (https://www.kaggle.com/mission-ai/crimeucfdataset)  dataset.

Is it possible to use same logic on top of UCF-CRCV ? 

Thanks,

**Comment by tcapelle** [comment]
of corse!
I use this pipeline to solve other kind of image-sequence problems.

**Comment by VinayChaudhari1996** [comment]
Thanks , 
Can you you share your core versions of fastai and necessary packages.

I'm getting issues while extracting frames. 
Fastai2 issues. 

It will helpful , if you share readme for any kind of video classification. 

1) Video data to frames (images) creation 
2) Model training 
3) loading trained model and Inference for local video or live video

**Comment by tcapelle** [comment]
the frame extraction is done in the notebook. I am not an exert on this, I just used a tool that seemed to work (av package). This is not a fastai issue.
This repo runs with latest fastai, you can clone it and install it:
```bash
git clone ....
cd action_recognition
pip install -e .
```

**Comment by VinayChaudhari1996** [comment]
Thanks it works for me :)
