### ISSUE TITLE
How to make inference on new video or image using trained model ?

### ISSUE THREAD

**Issue by actcod01** [tcapelle/action_recognition#18]
Hi @tcapelle ,

I really appreciate your efforts in making this open-source project.

> I have trained my model using your given steps and I got 96% accuracy. Now I want to use a trained model for inference

**1) New Video
2) Live Camera Feed
3) Image (jpg/png)**

How can I achieve that, can you share the code for that?

Thanks :)

**Comment by skyqwe123** [comment]
@actcod01 Have you solved the problem? I want to find a complete tutorial to study. Thanks.

**Comment by tcapelle** [comment]
I think openCV has tutorials on this, inference on this type of models is slow, so don't know if would work fast enough.
