### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by M-a-i** [tcapelle/action_recognition#20]
Sorry to bother you. I got an error as follows, how can I fix this ?

'''
File "/home/michael/action_recognition/action_recognition/models.py", line 256, in forward
    video = torch.stack(video, dim=1)  #to deal with the ImageTuple

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not TensorCategory
'''

**Comment by tcapelle** [comment]
good question, which notebooks produces this?

**Comment by tcapelle** [comment]
This is an issue on fastai 2.3.
Please add this cell before the Learner definition:
```python
@patch
def one_batch(self: Learner, i, b):
    self.iter = i
    b_on_device = to_device(b, device=self.dls.device) if self.dls.device is not None else b
    self._split(b_on_device)
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)
```

**Comment by tcapelle** [comment]
I am currently proposing a fix [here](https://github.com/fastai/fastai/pull/3298)

**Comment by M-a-i** [comment]
Thanks, it does work !
