### ISSUE TITLE
explaining ImageTupletfm

### ISSUE THREAD

**Issue by nikky4D** [tcapelle/action_recognition#24]
Hi,

I don't fully understand how to create the dataset. Can you clear up some confusing points please? In particular, 

- what does ImageTuple return? In imagetuple, does it return a figure from show() method or actual images?
- in dataset, what is the function parent_label? is it a fastai function?
- in dataset creation, the input "files" is a list of paths. each path is a folder containing images for that set. then to create a single (x,y) input to the model, the ImageTupletfm applies on the images from this path sampling them up to seq_len. the sampled set and the parent_label make the (x,y) result? Is this correct?

**Comment by tcapelle** [comment]
Hey, thanks for using this little project of mine:
- I encourage you to check this: 
https://tcapelle.github.io/pytorch/fastai/cv/2021/03/15/image_sequences.html
- `parent_label` is a fastai func:
```python
def parent_label(o):
    "Label `item` with the parent folder name."
    return Path(o).parent.name
```
-Yes

**Comment by nikky4D** [comment]
Thanks for information. One more question: what happens for videos of different lengths like if the video folder does not have enough samples? that is, if we want a seq_len of 20, but we have less than in the folder, how does the model deal with sequence lengths less that it expects?

**Comment by tcapelle** [comment]
it does not deal with different lenghts... please submit a PR if you make it work.

**Comment by nikky4D** [comment]
Thank you. I'm working on that now.
