### ISSUE TITLE
This appears to be an CNN-LSTM and not a ConvLSTM

### ISSUE THREAD

**Issue by rbunn80110** [tcapelle/action_recognition#3]
https://www.quora.com/What-is-the-difference-between-ConvLSTM-and-CNN-LSTM#:~:text=ConvLSTM%20is%20when%20you%20have,as%20a%20spatial%20feature%20extractor.

**Comment by tcapelle** [comment]
it is indeed

**Comment by rbunn80110** [comment]
The model you already created here worked great for my specific problem.  I'm curious to see if the conv_lstm based resnet will give better results or not.
