### ISSUE TITLE
Instructions to run baseline model

### ISSUE THREAD

**Issue by Soumi7** [tcapelle/action_recognition#4]
# Can we have one set of instructions for extraction of frames and running the model and getting the outputs ?

The notebooks are a bit confusing.

I have a dataset of 3 classes consisting of 25 videos each in the format of UCF101 and a traintest split file as well. 

So I require one set of instructions to run.(similar to the original repo)

**Comment by tcapelle** [comment]
The code provided is to run UCF.
You can adapt to run this on your own data, I have done so.
Take a tour on fastai2 tutorials to learn how to use the bricks.
