### ISSUE TITLE
Videos with different number of frames

### ISSUE THREAD

**Issue by samiit** [tcapelle/action_recognition#7]
Hi,

Thanks for sharing your solution. It is of great help for beginners to get familiar with using fastai2 for action detection.

I had a question about your custom data loader. I have a set of videos with different number of frames. I want to ensure that during training, the model should see the entire set of frames of each video. I see in your code you have selected a random frame location in the video and taken a fixed number of frames from that point on (as far as I understood). 

1. Do you have this functionality that the dataloader can show the model the entire set of frames, for each video. 

2. Does the model (baseline or ConvLSTM) require that the number of sequences be equal for all the videos in the input data? 

3. Especially, if I get another video tomorrow on which I need to make a prediction that might be of longer duration (than all the videos in the training set), would this model work?

Thanks,

Sam

**Comment by tcapelle** [comment]
Hey, thank you for your feedback.
- The problem with different lenght videos is the collate. You want to be able to stack together as a fat tensor the videos to feed the neural net. You could use different lengths videos and pad the shorter ones with black or tokens, like it is done with text. Right now the dataloaders does not support this.
- Inference with one video at a time with variable length should not be a problem.
