### ISSUE TITLE
 AssertionError  

### ISSUE THREAD

**Issue by Soumi7** [tcapelle/action_recognition#8]
I have 60 videos for training and 15 for testing.
I faced this error in 04_train_convlstm.ipynb
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-15-0a0f4116d3e6> in <module>()
      1 seq_len = 5
      2 image_size = 128
----> 3 assert len(files)/8 == len(files)//8

AssertionError: 
```

**Comment by tcapelle** [comment]
This is horribly hardcoded...
I am not taking care of the last element on the batch for the training dataloader.

**Comment by tcapelle** [comment]
Ok, it is fixed inside the LSTM class, it can deal with different batch sizes.
The assert is not needed.
