### ISSUE TITLE
How to check test accuracy?

### ISSUE THREAD

**Issue by Soumi7** [tcapelle/action_recognition#9]
You mentioned 91% accuracy on the test set.

The accuracies that are output during training are training accuracies right, and the best accuracy in your ``` 04_train_baseline.ipynb ``` is 49%. So where is the test set accuracy of 91%?

How to get the test accuracy after ``` learn.show_results() ``` ?

**Comment by samiit** [comment]
Can you try running: 

`learn.metrics`

**Comment by Soumi7** [comment]
@samiit I tried that ```learn.metrics``` at the end, this is the output i got :
```
(#1) [<fastai2.learner.AvgMetric object at 0x7f8c3c1bc080>]
```

**Comment by Soumi7** [comment]
```
learn.validate() 
```
This output :
```
(#2) [1.8338652849197388,0.5454545617103577]
```
So the validation accuracy is 54.5% ?

I found this in the fast.ai docs :
```
learn.validate(learn.data.valid_dl)
``` 
Which gives this error 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-e1c75c0d6084> in <module>()
----> 1 learn.validate(learn.data.valid_dl)

AttributeError: 'Learner' object has no attribute 'data'
```

**Comment by tcapelle** [comment]
To clarify, the 91% accuracy is with a random split.
The split used now is the split0 supplied with the dataset, it is much harder.
```
learn.validate() 
```
should give the validation loss with the metrics configured on the learner.

**Comment by tcapelle** [comment]
Is it running correctly for you guys now?

**Comment by samiit** [comment]
> You mentioned 91% accuracy on the test set.
> 
> The accuracies that are output during training are training accuracies right, and the best accuracy in your `04_train_baseline.ipynb` is 49%. So where is the test set accuracy of 91%?
> 

In principle, the metrics returned by fastai2 during the training process is **on the validation set**, after training on the training set. So what gets displayed during the training process as well as the value you've got using `learn.validate()` is the validation metrics.

**Comment by Soumi7** [comment]
Thanks! Got it.
